/* ============================================
   LogiCore AI – Macro Creator Agent
   Generate VBA macros or Office Scripts from
   a natural-language description.
   ============================================ */

import React, { useCallback, useState } from 'react';
import {
    Braces,
    Play,
    Copy,
    Check,
    RotateCcw,
    CircleDot,
    AlertTriangle,
} from 'lucide-react';
import { useLanguage } from '@/context/LanguageContext';
import { queryGemini } from '@/services/geminiService';
import { MacroInstructions } from '@/agents/macro-creator/MacroInstructions';

type ScriptType = 'vba' | 'officescript';

// ── System prompts per script type ────────────

const SYSTEM_PROMPTS: Record<ScriptType, string> = {
    vba: `You are an expert Excel VBA developer.
Generate clean, well-commented VBA code based on the user's description.
Rules:
- Always use Sub...End Sub with a descriptive English name
- Add a comment block at top: purpose, generated by LogiCore AI
- Declare all variables explicitly (Option Explicit style)
- Handle basic errors where appropriate
- If request is ambiguous, implement most logical interpretation and note it in comments
- Output VBA code ONLY – no markdown fences, no explanations outside comments`,

    officescript: `You are an expert Office Scripts developer for Excel Online (Microsoft 365).
Generate clean TypeScript-based Office Scripts code based on the user's description.
Rules:
- Always use: async function main(workbook: ExcelScript.Workbook) { }
- Add a comment block at top: purpose, generated by LogiCore AI
- Use proper ExcelScript API (getActiveWorksheet, getRange, etc.)
- Always use getRangeByIndexes with all 4 required parameters (rowIndex, columnIndex, rowCount, columnCount). Never call it with only 2 parameters.
- Always use worksheet.getUsedRange().getFormat().autofitColumns() instead of worksheet.getRange().getFormat().autofitColumns().
- Add inline comments explaining key steps
- If request is ambiguous, implement most logical interpretation and note it in comments
- Output Office Scripts code ONLY – no markdown fences, no explanations outside comments`,
};

// ── Post-processing for Office Scripts ────────
// Fixes common API mistakes that Gemini may produce.
function postProcessOfficeScript(code: string): string {
    // Fix getRangeByIndexes calls with only 2 parameters → append ", 1, 1"
    code = code.replace(
        /getRangeByIndexes\(\s*([^,)]+)\s*,\s*([^,)]+)\s*\)/g,
        'getRangeByIndexes($1, $2, 1, 1)'
    );

    // Replace getRange().getFormat().autofitColumns() with getUsedRange() variant
    code = code.replace(
        /\.getRange\(\)\s*\.getFormat\(\)\s*\.autofitColumns\(\)/g,
        '.getUsedRange().getFormat().autofitColumns()'
    );

    return code;
}

export const MacroCreator: React.FC = () => {
    const { t } = useLanguage();

    const [scriptType, setScriptType] = useState<ScriptType>('vba');
    const [description, setDescription] = useState('');
    const [generatedCode, setGeneratedCode] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [copied, setCopied] = useState(false);

    // Generate macro via /api/analyze
    const handleGenerate = useCallback(async () => {
        if (!description.trim()) return;

        setIsLoading(true);
        setError(null);
        setGeneratedCode('');

        try {
            const systemPrompt = SYSTEM_PROMPTS[scriptType];
            const fullPrompt = `${systemPrompt}\n\nUser request:\n${description.trim()}`;
            const result = await queryGemini(fullPrompt);

            // Strip any accidental markdown fences from response
            let code = result.trim();
            if (code.startsWith('```')) {
                const firstNewline = code.indexOf('\n');
                code = code.slice(firstNewline + 1);
            }
            if (code.endsWith('```')) {
                code = code.slice(0, -3).trimEnd();
            }

            // Post-process Office Scripts to fix common API mistakes
            if (scriptType === 'officescript') {
                code = postProcessOfficeScript(code);
            }

            setGeneratedCode(code);
        } catch (err: unknown) {
            const msg =
                err instanceof Error ? err.message : 'Generation failed';
            setError(msg);
        } finally {
            setIsLoading(false);
        }
    }, [description, scriptType]);

    // Copy to clipboard
    const handleCopy = useCallback(async () => {
        if (!generatedCode) return;
        try {
            await navigator.clipboard.writeText(generatedCode);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch {
            // Fallback for older browsers
            const textarea = document.createElement('textarea');
            textarea.value = generatedCode;
            document.body.appendChild(textarea);
            textarea.select();
            document.execCommand('copy');
            document.body.removeChild(textarea);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        }
    }, [generatedCode]);

    // Regenerate (keep description but clear output)
    const handleRegenerate = useCallback(() => {
        setGeneratedCode('');
        setError(null);
        // Re-trigger generation
        void handleGenerate();
    }, [handleGenerate]);

    const canGenerate = description.trim().length > 0 && !isLoading;

    return (
        <div className="max-w-screen-xl mx-auto px-6 py-8 animate-[fade-in_0.5s_ease-out]">
            {/* Agent Header */}
            <div className="flex items-start gap-4 mb-8">
                <div className="p-3 rounded-xl bg-gradient-to-br from-violet-600 to-purple-800 shadow-lg shadow-violet-900/20">
                    <Braces className="w-6 h-6 text-white" />
                </div>
                <div>
                    <h2 className="text-xl font-bold text-slate-900">
                        {t('macroCreator.title')}
                    </h2>
                    <p className="text-sm text-slate-500">
                        {t('macroCreator.description')}
                    </p>
                </div>
            </div>

            <div className="space-y-6">
                {/* Script Type Selector */}
                <div>
                    <label
                        htmlFor="macro-script-type"
                        className="block text-sm font-semibold text-slate-700 mb-2"
                    >
                        {t('macroCreator.selectTypeLabel')}
                    </label>
                    <select
                        id="macro-script-type"
                        value={scriptType}
                        onChange={(e) =>
                            setScriptType(e.target.value as ScriptType)
                        }
                        className="w-full max-w-md px-4 py-2.5 rounded-xl border border-slate-200 bg-white text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-violet-500/30 focus:border-violet-400 transition-all enterprise-shadow"
                    >
                        <option value="vba">
                            {t('macroCreator.typeVBA')}
                        </option>
                        <option value="officescript">
                            {t('macroCreator.typeOfficeScript')}
                        </option>
                    </select>
                </div>

                {/* Description Textarea */}
                <div>
                    <label
                        htmlFor="macro-description"
                        className="block text-sm font-semibold text-slate-700 mb-2"
                    >
                        {t('macroCreator.inputLabel')}
                    </label>
                    <textarea
                        id="macro-description"
                        value={description}
                        onChange={(e) => setDescription(e.target.value)}
                        placeholder={t('macroCreator.placeholder')}
                        disabled={isLoading}
                        className="w-full px-4 py-3 rounded-xl border border-slate-200 bg-white text-sm text-slate-700 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-violet-500/30 focus:border-violet-400 transition-all enterprise-shadow resize-y disabled:opacity-60"
                        style={{ minHeight: '120px' }}
                    />
                </div>

                {/* Generate Button */}
                <div className="flex items-center gap-3">
                    <button
                        onClick={handleGenerate}
                        disabled={!canGenerate}
                        className={`
                            flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold transition-all
                            ${
                                canGenerate
                                    ? 'bg-gradient-to-r from-violet-600 to-purple-700 text-white shadow-lg shadow-violet-600/20 hover:shadow-xl hover:shadow-violet-600/30 hover:-translate-y-0.5'
                                    : 'bg-slate-100 text-slate-400 cursor-not-allowed'
                            }
                        `}
                    >
                        <Play className="w-4 h-4" />
                        {t('macroCreator.generateButton')}
                    </button>
                </div>

                {/* Loading State */}
                {isLoading && (
                    <div className="bg-white rounded-xl p-6 enterprise-shadow animate-[slide-up_0.3s_ease-out]">
                        <div className="flex items-center gap-3">
                            <CircleDot className="w-5 h-5 text-violet-600 animate-spin" />
                            <p className="text-sm font-semibold text-slate-700">
                                {t('macroCreator.loadingText')}
                            </p>
                        </div>
                        <div className="mt-3 w-full h-2 rounded-full bg-slate-100 overflow-hidden">
                            <div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-purple-600 animate-pulse w-2/3" />
                        </div>
                    </div>
                )}

                {/* Error State */}
                {error && (
                    <div className="bg-red-50 border border-red-200 rounded-xl p-4 flex items-start gap-3">
                        <AlertTriangle className="w-5 h-5 text-red-500 mt-0.5 flex-shrink-0" />
                        <div>
                            <p className="text-sm font-semibold text-red-700">
                                {t('macroCreator.generationFailed')}
                            </p>
                            <p className="text-xs text-red-600 mt-0.5">
                                {error}
                            </p>
                        </div>
                    </div>
                )}

                {/* Generated Code Output */}
                {generatedCode && (
                    <div className="space-y-4 animate-[slide-up_0.4s_ease-out]">
                        {/* Code Block */}
                        <div className="rounded-xl overflow-hidden enterprise-shadow">
                            <div className="bg-slate-800 px-4 py-2.5 flex items-center justify-between">
                                <span className="text-xs font-medium text-slate-400 uppercase tracking-wider">
                                    {scriptType === 'vba'
                                        ? 'VBA'
                                        : 'Office Script'}
                                </span>
                                <div className="flex items-center gap-2">
                                    {/* Copy Button */}
                                    <button
                                        onClick={handleCopy}
                                        className="flex items-center gap-1.5 px-3 py-1 rounded-md text-xs font-medium text-slate-300 hover:bg-slate-700 transition-colors"
                                    >
                                        {copied ? (
                                            <>
                                                <Check className="w-3.5 h-3.5 text-emerald-400" />
                                                <span className="text-emerald-400">
                                                    {t(
                                                        'macroCreator.copiedText'
                                                    )}
                                                </span>
                                            </>
                                        ) : (
                                            <>
                                                <Copy className="w-3.5 h-3.5" />
                                                {t('macroCreator.copyButton')}
                                            </>
                                        )}
                                    </button>
                                </div>
                            </div>
                            <div className="bg-slate-900 p-4 overflow-x-auto">
                                <pre className="text-sm text-slate-200 font-mono leading-relaxed whitespace-pre">
                                    {generatedCode}
                                </pre>
                            </div>
                        </div>

                        {/* Regenerate Button */}
                        <button
                            onClick={handleRegenerate}
                            disabled={isLoading}
                            className="flex items-center gap-1.5 px-4 py-2.5 rounded-xl text-sm font-medium text-slate-500 hover:bg-slate-100 transition-colors"
                        >
                            <RotateCcw className="w-3.5 h-3.5" />
                            {t('macroCreator.regenerateButton')}
                        </button>
                    </div>
                )}

                {/* Instructions – always visible below output */}
                <MacroInstructions type={scriptType} />
            </div>
        </div>
    );
};
